// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package order

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeleteReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReq) Reset()         { *m = DeleteReq{} }
func (m *DeleteReq) String() string { return proto.CompactTextString(m) }
func (*DeleteReq) ProtoMessage()    {}
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *DeleteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReq.Unmarshal(m, b)
}
func (m *DeleteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReq.Marshal(b, m, deterministic)
}
func (m *DeleteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReq.Merge(m, src)
}
func (m *DeleteReq) XXX_Size() int {
	return xxx_messageInfo_DeleteReq.Size(m)
}
func (m *DeleteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReq proto.InternalMessageInfo

func (m *DeleteReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Req struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Req) Reset()         { *m = Req{} }
func (m *Req) String() string { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()    {}
func (*Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Req.Unmarshal(m, b)
}
func (m *Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Req.Marshal(b, m, deterministic)
}
func (m *Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Req.Merge(m, src)
}
func (m *Req) XXX_Size() int {
	return xxx_messageInfo_Req.Size(m)
}
func (m *Req) XXX_DiscardUnknown() {
	xxx_messageInfo_Req.DiscardUnknown(m)
}

var xxx_messageInfo_Req proto.InternalMessageInfo

func (m *Req) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type Res struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 []*Order `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Res) Reset()         { *m = Res{} }
func (m *Res) String() string { return proto.CompactTextString(m) }
func (*Res) ProtoMessage()    {}
func (*Res) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2}
}

func (m *Res) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Res.Unmarshal(m, b)
}
func (m *Res) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Res.Marshal(b, m, deterministic)
}
func (m *Res) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Res.Merge(m, src)
}
func (m *Res) XXX_Size() int {
	return xxx_messageInfo_Res.Size(m)
}
func (m *Res) XXX_DiscardUnknown() {
	xxx_messageInfo_Res.DiscardUnknown(m)
}

var xxx_messageInfo_Res proto.InternalMessageInfo

func (m *Res) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Res) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Res) GetData() []*Order {
	if m != nil {
		return m.Data
	}
	return nil
}

type Order struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedOn            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	ModifiedOn           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=modifiedOn,proto3" json:"modifiedOn,omitempty"`
	DeletedOn            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=deletedOn,proto3" json:"deletedOn,omitempty"`
	StoreId              int64                `protobuf:"varint,5,opt,name=storeId,proto3" json:"storeId,omitempty"`
	UserUid              string               `protobuf:"bytes,6,opt,name=userUid,proto3" json:"userUid,omitempty"`
	OrderNo              string               `protobuf:"bytes,7,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	PayNo                string               `protobuf:"bytes,8,opt,name=payNo,proto3" json:"payNo,omitempty"`
	LogisticsNo          string               `protobuf:"bytes,9,opt,name=logisticsNo,proto3" json:"logisticsNo,omitempty"`
	OrderStatus          int64                `protobuf:"varint,10,opt,name=orderStatus,proto3" json:"orderStatus,omitempty"`
	OriginFee            float64              `protobuf:"fixed64,11,opt,name=originFee,proto3" json:"originFee,omitempty"`
	PayFee               float64              `protobuf:"fixed64,15,opt,name=payFee,proto3" json:"payFee,omitempty"`
	PayTime              *timestamp.Timestamp `protobuf:"bytes,16,opt,name=payTime,proto3" json:"payTime,omitempty"`
	UserMem              string               `protobuf:"bytes,37,opt,name=userMem,proto3" json:"userMem,omitempty"`
	IsStore              bool                 `protobuf:"varint,38,opt,name=isStore,proto3" json:"isStore,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{3}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Order) GetCreatedOn() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedOn
	}
	return nil
}

func (m *Order) GetModifiedOn() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedOn
	}
	return nil
}

func (m *Order) GetDeletedOn() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedOn
	}
	return nil
}

func (m *Order) GetStoreId() int64 {
	if m != nil {
		return m.StoreId
	}
	return 0
}

func (m *Order) GetUserUid() string {
	if m != nil {
		return m.UserUid
	}
	return ""
}

func (m *Order) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *Order) GetPayNo() string {
	if m != nil {
		return m.PayNo
	}
	return ""
}

func (m *Order) GetLogisticsNo() string {
	if m != nil {
		return m.LogisticsNo
	}
	return ""
}

func (m *Order) GetOrderStatus() int64 {
	if m != nil {
		return m.OrderStatus
	}
	return 0
}

func (m *Order) GetOriginFee() float64 {
	if m != nil {
		return m.OriginFee
	}
	return 0
}

func (m *Order) GetPayFee() float64 {
	if m != nil {
		return m.PayFee
	}
	return 0
}

func (m *Order) GetPayTime() *timestamp.Timestamp {
	if m != nil {
		return m.PayTime
	}
	return nil
}

func (m *Order) GetUserMem() string {
	if m != nil {
		return m.UserMem
	}
	return ""
}

func (m *Order) GetIsStore() bool {
	if m != nil {
		return m.IsStore
	}
	return false
}

func init() {
	proto.RegisterType((*DeleteReq)(nil), "order.DeleteReq")
	proto.RegisterType((*Req)(nil), "order.Req")
	proto.RegisterType((*Res)(nil), "order.Res")
	proto.RegisterType((*Order)(nil), "order.Order")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 444 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x25, 0x4d, 0xbf, 0x32, 0x41, 0x50, 0x8d, 0x10, 0xb2, 0x0a, 0x12, 0x51, 0x04, 0x6c, 0x39,
	0x90, 0x95, 0x0a, 0x07, 0xc4, 0x15, 0x04, 0xe2, 0xd0, 0xae, 0x94, 0xb2, 0x3f, 0x20, 0x5b, 0xcf,
	0x46, 0x96, 0x9a, 0x75, 0x36, 0x76, 0x91, 0xfa, 0x2b, 0xf8, 0x2d, 0xfc, 0x43, 0xe4, 0x71, 0xd2,
	0x16, 0x38, 0x84, 0x4b, 0xe4, 0x37, 0xef, 0x79, 0xec, 0xf7, 0x32, 0x86, 0x58, 0x37, 0x92, 0x9a,
	0xac, 0x6e, 0xb4, 0xd5, 0x38, 0x62, 0x30, 0x7f, 0x51, 0x6a, 0x5d, 0xee, 0xe8, 0x92, 0x8b, 0x37,
	0xfb, 0xdb, 0x4b, 0xab, 0x2a, 0x32, 0xb6, 0xa8, 0x6a, 0xaf, 0x4b, 0x9f, 0x41, 0xf4, 0x99, 0x76,
	0x64, 0x29, 0xa7, 0x7b, 0x7c, 0x04, 0x03, 0x25, 0x45, 0x90, 0x04, 0x8b, 0x30, 0x1f, 0x28, 0x99,
	0xbe, 0x81, 0xd0, 0x95, 0x53, 0xf0, 0xdd, 0x98, 0x89, 0x97, 0x0f, 0x33, 0x7f, 0xd0, 0x95, 0xfb,
	0xe6, 0x9e, 0x4a, 0x57, 0x4e, 0x6a, 0x10, 0x61, 0xb8, 0xd5, 0x92, 0xda, 0x1e, 0xbc, 0xc6, 0x19,
	0x84, 0x95, 0x29, 0xc5, 0x20, 0x09, 0x16, 0x51, 0xee, 0x96, 0x98, 0xc0, 0x50, 0x16, 0xb6, 0x10,
	0x61, 0x12, 0xfe, 0xd3, 0x8f, 0x99, 0xf4, 0xe7, 0x10, 0x46, 0x8c, 0xff, 0xbe, 0x13, 0x7e, 0x80,
	0x68, 0xdb, 0x50, 0x61, 0x49, 0x5e, 0xdd, 0x71, 0xcf, 0x78, 0x39, 0xcf, 0xbc, 0xcb, 0xac, 0x73,
	0x99, 0x7d, 0xef, 0x5c, 0xe6, 0x27, 0x31, 0x7e, 0x04, 0xa8, 0xb4, 0x54, 0xb7, 0x8a, 0xb7, 0x86,
	0xbd, 0x5b, 0xcf, 0xd4, 0xee, 0x54, 0xc9, 0x31, 0xb9, 0xad, 0xc3, 0xfe, 0x53, 0x8f, 0x62, 0x14,
	0x30, 0x31, 0x56, 0x37, 0xf4, 0x4d, 0x8a, 0x11, 0x9b, 0xe8, 0xa0, 0x63, 0xf6, 0x86, 0x9a, 0x6b,
	0x25, 0xc5, 0x98, 0xb3, 0xe9, 0xa0, 0x63, 0x38, 0x92, 0xb5, 0x16, 0x13, 0xcf, 0xb4, 0x10, 0x9f,
	0xc0, 0xa8, 0x2e, 0x0e, 0x6b, 0x2d, 0xa6, 0x5c, 0xf7, 0x00, 0x13, 0x88, 0x77, 0xba, 0x54, 0xc6,
	0xaa, 0xad, 0x59, 0x6b, 0x11, 0x31, 0x77, 0x5e, 0x72, 0x0a, 0x6e, 0xb1, 0xb1, 0x85, 0xdd, 0x1b,
	0x01, 0x7c, 0x93, 0xf3, 0x12, 0x3e, 0x87, 0x48, 0x37, 0xaa, 0x54, 0x77, 0x5f, 0x88, 0x44, 0x9c,
	0x04, 0x8b, 0x20, 0x3f, 0x15, 0xf0, 0x29, 0x8c, 0xeb, 0xe2, 0xe0, 0xa8, 0xc7, 0x4c, 0xb5, 0x08,
	0xdf, 0xc3, 0xa4, 0x2e, 0x0e, 0xce, 0xb8, 0x98, 0xf5, 0xa6, 0xd2, 0x49, 0x3b, 0xe7, 0x2b, 0xaa,
	0xc4, 0xab, 0x93, 0xf3, 0x15, 0x55, 0x8e, 0x51, 0x66, 0xe3, 0x02, 0x12, 0xaf, 0x93, 0x60, 0x31,
	0xcd, 0x3b, 0xb8, 0xfc, 0x15, 0xc0, 0x94, 0x27, 0x62, 0xd3, 0xfc, 0xc0, 0x0b, 0x88, 0x3f, 0xf1,
	0x7f, 0xf5, 0x33, 0x02, 0xed, 0x04, 0xe5, 0x74, 0x3f, 0x3f, 0xad, 0x4d, 0xfa, 0x00, 0x5f, 0xc2,
	0xf4, 0x2b, 0xd9, 0x3e, 0xd5, 0x05, 0xc4, 0xd7, 0xb5, 0xfc, 0x8f, 0x76, 0x6f, 0x21, 0xf6, 0xaf,
	0xc5, 0x0b, 0x67, 0x2d, 0x79, 0x7c, 0x41, 0x7f, 0xca, 0x6f, 0xc6, 0x1c, 0xc2, 0xbb, 0xdf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x72, 0xfd, 0xf0, 0x13, 0x9a, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderSrvClient is the client API for OrderSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderSrvClient interface {
	CreateOrder(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error)
	GetOrder(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error)
	UpdateOrder(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error)
	DeleteOrder(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*Res, error)
}

type orderSrvClient struct {
	cc *grpc.ClientConn
}

func NewOrderSrvClient(cc *grpc.ClientConn) OrderSrvClient {
	return &orderSrvClient{cc}
}

func (c *orderSrvClient) CreateOrder(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/order.OrderSrv/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderSrvClient) GetOrder(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/order.OrderSrv/GetOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderSrvClient) UpdateOrder(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/order.OrderSrv/UpdateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderSrvClient) DeleteOrder(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/order.OrderSrv/DeleteOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderSrvServer is the server API for OrderSrv service.
type OrderSrvServer interface {
	CreateOrder(context.Context, *Req) (*Res, error)
	GetOrder(context.Context, *Req) (*Res, error)
	UpdateOrder(context.Context, *Req) (*Res, error)
	DeleteOrder(context.Context, *DeleteReq) (*Res, error)
}

// UnimplementedOrderSrvServer can be embedded to have forward compatible implementations.
type UnimplementedOrderSrvServer struct {
}

func (*UnimplementedOrderSrvServer) CreateOrder(ctx context.Context, req *Req) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (*UnimplementedOrderSrvServer) GetOrder(ctx context.Context, req *Req) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrder not implemented")
}
func (*UnimplementedOrderSrvServer) UpdateOrder(ctx context.Context, req *Req) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrder not implemented")
}
func (*UnimplementedOrderSrvServer) DeleteOrder(ctx context.Context, req *DeleteReq) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOrder not implemented")
}

func RegisterOrderSrvServer(s *grpc.Server, srv OrderSrvServer) {
	s.RegisterService(&_OrderSrv_serviceDesc, srv)
}

func _OrderSrv_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderSrvServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderSrv/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderSrvServer).CreateOrder(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderSrv_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderSrvServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderSrv/GetOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderSrvServer).GetOrder(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderSrv_UpdateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderSrvServer).UpdateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderSrv/UpdateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderSrvServer).UpdateOrder(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderSrv_DeleteOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderSrvServer).DeleteOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderSrv/DeleteOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderSrvServer).DeleteOrder(ctx, req.(*DeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderSrv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderSrv",
	HandlerType: (*OrderSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderSrv_CreateOrder_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _OrderSrv_GetOrder_Handler,
		},
		{
			MethodName: "UpdateOrder",
			Handler:    _OrderSrv_UpdateOrder_Handler,
		},
		{
			MethodName: "DeleteOrder",
			Handler:    _OrderSrv_DeleteOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
